- repo: https://github.com/psf/black-pre-commit-mirror
  hooks:
    - id: black
      language_version: 3.12

- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
